### ISSUE TITLE
Calibration Service Header UUID assignment for setParam

### ISSUE THREAD

**Issue by NET-Code-Dev** [pcolby/dokit#17]
In the calibrationservices.h  the setParam UUID appears to have an extra trailing '4'. 

When I log this, I get the UUID as: 5588e47b-cb81-4f7b-acc4-6029a3f39f72

**Comment by pcolby** [comment]
Thanks @NET-Code-Dev, you are correct. The UUID with an extra trailing `4` is not even a valid UUID. I've done a quick regex match against all UUIDs in the code base, and this is the only invalid one - presumably a cut-and-paste error on my part.

I will fix this up and release a new version (v0.5.1) later today.

Thanks!

**Comment by pcolby** [comment]
[v0.5.1](https://github.com/pcolby/dokit/releases/tag/v0.5.1) has now been released 😊
