### ISSUE TITLE
Compile on Windows

### ISSUE THREAD

**Issue by hvdkooij** [pcolby/dokit#19]
Does someone has a good pointer on instructions on getting the proper tools on a windows machine to compile this?
I guess my queries were not good in Google and I did not find any relevant documents. On linux this is so much easier but I need a windows executable for presentation purposes of signals we measure with on a digital train layout.

**Comment by pcolby** [comment]
Hi @hvdkooij,

> instructions on getting the proper tools on a windows machine to compile this?

Once you've installed Qt and MSVC, you should be able to build on Windows just the same as on Linux, eg:

```sh
cmake.exe -D CMAKE_BUILD_TYPE=Release -S <path-to-cloned-repo> -B <tmp-build-dir>
cmake.exe --build <tmp-build-dir>
```

Depending on how you installed Qt, you might need to add Qt to your path first. Or, perhaps even easier, use Qt's `qt-cmake` wrapper, like:

```sh
X:\path\to\qt\bin\qt-cmake -D CMAKE_BUILD_TYPE=Release -S <path-to-cloned-repo> -B <tmp-build-dir>
X:\path\to\qt\bin\qt-cmake --build <tmp-build-dir>
```

That's what I do when building locally for development (though I set a few other flags to enable some features like documentation generation too).

For further inspiration, you can see how the official Windows releases are built in CI here: https://github.com/pcolby/dokit/blob/main/.github/workflows/build.yaml#L271

> I need a windows executable for presentation purposes

Have you tried a portable release from the [Releases](https://github.com/pcolby/dokit/releases) page? eg [dokit-0.5.1+923.win.x86-64.msvc.qt-6.6.1.portable.zip](https://github.com/pcolby/dokit/releases/download/v0.5.1/dokit-0.5.1+923.win.x86-64.msvc.qt-6.6.1.portable.zip) That's where I'd recommend you start on Window.

Cheers.
